### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ziceptor** [JamieS1211/MineReset#3]
real number percentages per block

**Comment by JamieS1211** [comment]
Hey, can you please clarify this request? Do you mean you want 70% to be typed in as 70 in stead of 0.7?

**Comment by ziceptor** [comment]
```
            ores {
                "1" {
                    BlockState="minecraft:gold_ore"
                    percentage=0.5
                }
                "2" {
                    BlockState="minecraft:iron_ore"
                    percentage=0.1
                }

```

**Comment by JamieS1211** [comment]
Sorry I still don't fully understand this. In the config the percentage is the given percentage so 0.1 will be 1 in 1000 chance that that block is placed. In the commands in game the decimal form of the percentage is used so 0.1 would be 1 in 10 as 1 is the whole (100%). Is this what you want changed?
