### ISSUE TITLE
Wood mines

### ISSUE THREAD

**Issue by HaleyJayne** [JamieS1211/MineReset#7]
I made a wood mine on my server with all 6 types of wood, logs only, in the standing position. For some reason, they can mine some blocks but not others, and sometimes they can only mine in certain areas. I've unclaimed, reclaimed, added claim flags, etc. For some reason, this has always happened whenever I make a wood mine. Any idea as to what could be causing this?

**Comment by JamieS1211** [comment]
It is possible that some areas fall within the vanila block protection around the world spawn point. This code does not in any way modify block breaking interactions. Also sorry for the late response, hope you managed to sort this out.

**Comment by HaleyJayne** [comment]
I've had this issue on two servers already, for some reason it's always
wood logs, I changed it to wood planks and it's worked perfectly fine
without me having to move it nor change any claim flags or spawn protection
preferences. I'd just like to change it back to logs because my players are
literally the biggest babies, but I had to set up warp plates to tp them to
the other side because for some reason, the back end of the mine works
perfectly fine, the entrance at the front just won't let them in, which
makes no sense. Especially since I switched the mines to planks and you can
mine at the entrance just fine. In the previous server I had this on, there
was a vertical mine that was broken as well, except the broken clusters
were more sporadic and no focused on the entrance. Sorry for the paragraph,
just wanting to figure this out xD
